module.exports = {
  USER_ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    FACILITATOR: 'FACILITATOR',
    STUDENT: 'STUDENT'
  },
  
  ACTIVITY_STATUS: {
    DONE: 'DONE',
    PENDING: 'PENDING',
    NOT_STARTED: 'NOT_STARTED'
  },
  
  TRIMESTERS: {
    T1: 'T1',
    T2: 'T2',
    T3: 'T3'
  },
  
  INTAKE_PERIODS: {
    HT1: 'HT1',
    HT2: 'HT2',
    FT: 'FT'
  },
  
  MODES: {
    ONLINE: 'ONLINE',
    IN_PERSON: 'IN_PERSON',
    HYBRID: 'HYBRID'
  },
  
  MAX_WEEK_NUMBER: 16,
  MIN_WEEK_NUMBER: 1,
  
  NOTIFICATION_TYPES: {
    ACTIVITY_SUBMITTED: 'ACTIVITY_SUBMITTED',
    MISSING_LOGS_REMINDER: 'MISSING_LOGS_REMINDER',
    DEADLINE_MISSED: 'DEADLINE_MISSED',
    FACILITATOR_DEADLINE_MISSED: 'FACILITATOR_DEADLINE_MISSED'
  }
};